const Product = require("../src/models/product");
const { sequelize } = require("../src/config/database");

const seedProducts = async () => {
  try {
    // Sync database - force: true sẽ xóa toàn bộ dữ liệu cũ
    await sequelize.sync({ force: true });

    const products = [
      // Electronics - Bán chạy
      {
        name: "Samsung Galaxy S21",
        description: "Điện thoại flagship cao cấp với màn hình AMOLED 120Hz",
        price: 15999000,
        stock: 50,
        sold: 250,
        category: "Electronics",
        images: ["https://via.placeholder.com/300?text=Samsung+S21"],
        isPromotion: true,
        viewCount: 1850,
      },
      {
        name: "iPhone 13 Pro",
        description: "Điện thoại Apple cao cấp với chip A15 Bionic",
        price: 22999000,
        stock: 30,
        sold: 180,
        category: "Electronics",
        images: ["https://via.placeholder.com/300?text=iPhone+13+Pro"],
        isPromotion: false,
        viewCount: 2100,
      },
      {
        name: "MacBook Pro 14 inch",
        description: "Laptop chuyên nghiệp với chip M1 Pro",
        price: 39999000,
        stock: 20,
        sold: 95,
        category: "Electronics",
        images: ["https://via.placeholder.com/300?text=MacBook+Pro"],
        isPromotion: true,
        viewCount: 1650,
      },
      {
        name: "iPad Air 5",
        description: "Máy tính bảng cao cấp 10.9 inch",
        price: 18499000,
        stock: 40,
        sold: 150,
        category: "Electronics",
        images: ["https://via.placeholder.com/300?text=iPad+Air"],
        isPromotion: false,
        viewCount: 1200,
      },
      {
        name: "Sony WH-1000XM4",
        description: "Tai nghe chống ồn cao cấp",
        price: 8499000,
        stock: 60,
        sold: 320,
        category: "Electronics",
        images: ["https://via.placeholder.com/300?text=Sony+Headphones"],
        isPromotion: true,
        viewCount: 2450,
      },
      // Fashion - Xem nhiều
      {
        name: "Áo Polo nam cao cấp",
        description: "Áo polo cotton 100% thoáng mát",
        price: 499000,
        stock: 100,
        sold: 280,
        category: "Fashion",
        images: ["https://via.placeholder.com/300?text=Polo+Shirt"],
        isPromotion: true,
        viewCount: 3200,
      },
      {
        name: "Quần jeans đen clas ic",
        description: "Quần jeans denim chất lượng cao",
        price: 699000,
        stock: 80,
        sold: 220,
        category: "Fashion",
        images: ["https://via.placeholder.com/300?text=Jeans"],
        isPromotion: false,
        viewCount: 2800,
      },
      {
        name: "Giày thể thao Nike Air Force",
        description: "Giày sneaker cổ điển Nike",
        price: 2199000,
        stock: 50,
        sold: 190,
        category: "Fashion",
        images: ["https://via.placeholder.com/300?text=Nike+Shoes"],
        isPromotion: true,
        viewCount: 2950,
      },
      {
        name: "Túi xách da công sở",
        description: "Túi da cao cấp phù hợp công sở",
        price: 1899000,
        stock: 35,
        sold: 85,
        category: "Fashion",
        images: ["https://via.placeholder.com/300?text=Leather+Bag"],
        isPromotion: false,
        viewCount: 1950,
      },
      {
        name: "Đồng hồ nam Citizen",
        description: "Đồng hồ thời trang nam",
        price: 3499000,
        stock: 25,
        sold: 65,
        category: "Fashion",
        images: ["https://via.placeholder.com/300?text=Citizen+Watch"],
        isPromotion: true,
        viewCount: 1750,
      },
      // Home & Garden
      {
        name: "Đèn LED thông minh Philips Hue",
        description: "Bóng đèn LED WiFi thay đổi màu sắc",
        price: 799000,
        stock: 70,
        sold: 210,
        category: "Home & Garden",
        images: ["https://via.placeholder.com/300?text=Smart+Bulb"],
        isPromotion: true,
        viewCount: 2100,
      },
      {
        name: "Máy lọc không khí Xiaomi",
        description: "Máy lọc không khí cho phòng 30-40m2",
        price: 1299000,
        stock: 45,
        sold: 130,
        category: "Home & Garden",
        images: ["https://via.placeholder.com/300?text=Air+Purifier"],
        isPromotion: false,
        viewCount: 1650,
      },
      // Sports & Outdoors
      {
        name: "Vợt cầu lông Yonex Nanoray",
        description: "Vợt cầu lông chuyên nghiệp",
        price: 2499000,
        stock: 30,
        sold: 75,
        category: "Sports & Outdoors",
        images: ["https://via.placeholder.com/300?text=Badminton+Racket"],
        isPromotion: false,
        viewCount: 950,
      },
      {
        name: "Xe đạp địa hình XCR",
        description: "Xe đạp leo núi 24 inch, 21 số",
        price: 3999000,
        stock: 15,
        sold: 45,
        category: "Sports & Outdoors",
        images: ["https://via.placeholder.com/300?text=Mountain+Bike"],
        isPromotion: true,
        viewCount: 1400,
      },
      // Books
      {
        name: "Lập trình JavaScript từ A đến Z",
        description: "Sách hướng dẫn lập trình JavaScript toàn diện",
        price: 189000,
        stock: 200,
        sold: 450,
        category: "Books",
        images: ["https://via.placeholder.com/300?text=JS+Book"],
        isPromotion: true,
        viewCount: 2600,
      },
      {
        name: "Tư duy lập trình",
        description: "Cuốn sách giúp lập trình viên phát triển tư duy",
        price: 159000,
        stock: 150,
        sold: 320,
        category: "Books",
        images: ["https://via.placeholder.com/300?text=Programming+Mindset"],
        isPromotion: false,
        viewCount: 2200,
      },
      // Add more products to reach 20+ items for testing
      {
        name: "Webcam Logitech C920",
        description: "Webcam FHD 1080p cho streaming",
        price: 1199000,
        stock: 55,
        sold: 140,
        category: "Electronics",
        images: ["https://via.placeholder.com/300?text=Logitech+Webcam"],
        isPromotion: true,
        viewCount: 1580,
      },
      {
        name: "Chuột game Razer DeathAdder",
        description: "Chuột game với 5 nút lập trình",
        price: 899000,
        stock: 65,
        sold: 190,
        category: "Electronics",
        images: ["https://via.placeholder.com/300?text=Razer+Mouse"],
        isPromotion: false,
        viewCount: 1820,
      },
      {
        name: "Bàn phím cơ Ducky",
        description: "Bàn phím cơ RGB cao cấp",
        price: 2699000,
        stock: 40,
        sold: 110,
        category: "Electronics",
        images: ["https://via.placeholder.com/300?text=Ducky+Keyboard"],
        isPromotion: true,
        viewCount: 1450,
      },
      {
        name: "Áo khoác gió nam",
        description: "Áo khoác chống gió, nhẹ, thoáng khí",
        price: 899000,
        stock: 90,
        sold: 260,
        category: "Fashion",
        images: ["https://via.placeholder.com/300?text=Windbreaker"],
        isPromotion: true,
        viewCount: 2780,
      },
      {
        name: "Nước hoa Sauvage Dior",
        description: "Nước hoa nam cao cấp 100ml",
        price: 1599000,
        stock: 25,
        sold: 95,
        category: "Fashion",
        images: ["https://via.placeholder.com/300?text=Dior+Sauvage"],
        isPromotion: false,
        viewCount: 1690,
      },
    ];

    await Product.bulkCreate(products);
    console.log(`✅ Seeded ${products.length} products successfully`);
  } catch (error) {
    console.error("❌ Error seeding products:", error);
  } finally {
    await sequelize.close();
  }
};

seedProducts();
